// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9gLY0c4C9W1bfkL_Xr-rAgiuBo9YeF7E',
    appId: '1:191638601682:web:363da6f5f6a8edd25c520b',
    messagingSenderId: '191638601682',
    projectId: 'kitchencue-a4d6d',
    authDomain: 'kitchencue-a4d6d.firebaseapp.com',
    storageBucket: 'kitchencue-a4d6d.firebasestorage.app',
    measurementId: 'G-SLRW8SGPXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkI-y9PyeASbJAcSpV5U_PpWXCCKMzytc',
    appId: '1:191638601682:android:f982c71d45519a4e5c520b',
    messagingSenderId: '191638601682',
    projectId: 'kitchencue-a4d6d',
    storageBucket: 'kitchencue-a4d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTX-xPxGR8VHumQMCJWtC2ih59E1UnEs',
    appId: '1:191638601682:ios:d5c183da34b7fc765c520b',
    messagingSenderId: '191638601682',
    projectId: 'kitchencue-a4d6d',
    storageBucket: 'kitchencue-a4d6d.firebasestorage.app',
    iosBundleId: 'com.example.kitchenCue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTX-xPxGR8VHumQMCJWtC2ih59E1UnEs',
    appId: '1:191638601682:ios:d5c183da34b7fc765c520b',
    messagingSenderId: '191638601682',
    projectId: 'kitchencue-a4d6d',
    storageBucket: 'kitchencue-a4d6d.firebasestorage.app',
    iosBundleId: 'com.example.kitchenCue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9gLY0c4C9W1bfkL_Xr-rAgiuBo9YeF7E',
    appId: '1:191638601682:web:c4b53d0c54be69f35c520b',
    messagingSenderId: '191638601682',
    projectId: 'kitchencue-a4d6d',
    authDomain: 'kitchencue-a4d6d.firebaseapp.com',
    storageBucket: 'kitchencue-a4d6d.firebasestorage.app',
    measurementId: 'G-9XNRZRET1J',
  );
}
